# This GitHub Actions workflow is designed for Continuous Integration (CI) on a Next.js template project.
# It triggers on pull requests to the 'main' and 'dev' branches.
#
# The workflow consists of a single job named 'build' that runs on an Ubuntu 22.04 environment.
# It uses a matrix strategy to specify Node.js version 20.
#
# The job includes the following steps:
# 1. Checkout the repository using the actions/checkout@v4 action.
# 2. Install pnpm (version 9) using the pnpm/action-setup@v4 action.
# 3. Set up Node.js with the specified version and enable pnpm caching using the actions/setup-node@v4 action.
# 4. Install project dependencies using pnpm.
# 5. Run tests using the 'pnpm test' command.
# 6. Lint the code using the 'pnpm lint' command.
# 7. Format the code using the 'pnpm format' command.
name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test

      - name: Lint Code
        run: pnpm lint

      - name: Format Code
        run: pnpm format
